# Generated by Django 4.1.2 on 2023-04-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpass', '0002_alter_location_website_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='website_password',
            field=models.CharField(max_length=500),
        ),
    ]
